import type { Metadata } from "next";
import { CartProvider } from "@/context/CartContext";
import { Caveat, Poppins } from "next/font/google";
import "./globals.css";

const caveat = Caveat({ subsets: ["latin"], variable: "--font-caveat" });
const poppins = Poppins({
  subsets: ["latin"],
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
  style: ["normal", "italic"],
  variable: "--font-poppins",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`min-h-full flex flex-col ${poppins.variable} ${caveat.variable} font-poppins antialiased bg-background text-foreground selection:bg-brand-gold selection:text-white`}>
        <CartProvider>
          {children}
        </CartProvider>
      </body>
    </html>
  );
}
